# Generated by Django 4.1 on 2022-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_book_pages_alter_program_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
