# Generated by Django 4.1 on 2022-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_book_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
