# Generated by Django 4.1 on 2022-09-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
